services:
  - type: web
    name: weekwise
    env: docker
    plan: free
    dockerCommand: "" 
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
