// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Weekwise.Infrastructure.Data;

#nullable disable

namespace Weekwise.Infrastructure.Migrations
{
    [DbContext(typeof(WeekwiseDbContext))]
    [Migration("20260306115317_SeedNewTeamMembers")]
    partial class SeedNewTeamMembers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("Weekwise.Core.Entities.BacklogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedHours")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsArchived");

                    b.ToTable("BacklogItems");
                });

            modelBuilder.Entity("Weekwise.Core.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("Weekwise.Core.Entities.PlanMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WeeklyPlanId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("WeeklyPlanId", "MemberId")
                        .IsUnique();

                    b.ToTable("PlanMembers");
                });

            modelBuilder.Entity("Weekwise.Core.Entities.ProgressUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("HoursCompleted")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkCommitmentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("WorkCommitmentId");

                    b.ToTable("ProgressUpdates");
                });

            modelBuilder.Entity("Weekwise.Core.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeeklyCapacityHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "prajwal@demo.com",
                            IsActive = true,
                            Name = "Prajwal Dinde",
                            PasswordHash = "seeded",
                            Role = "Admin",
                            WeeklyCapacityHours = 40
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "ajay@demo.com",
                            IsActive = true,
                            Name = "Ajay more",
                            PasswordHash = "seeded",
                            Role = "Member",
                            WeeklyCapacityHours = 40
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "om@demo.com",
                            IsActive = true,
                            Name = "Om Patil",
                            PasswordHash = "seeded",
                            Role = "Member",
                            WeeklyCapacityHours = 40
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Email = "yash@demo.com",
                            IsActive = true,
                            Name = "Yash Gaikwad",
                            PasswordHash = "seeded",
                            Role = "Member",
                            WeeklyCapacityHours = 40
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Email = "jay@demo.com",
                            IsActive = true,
                            Name = "Jay Sharma",
                            PasswordHash = "seeded",
                            Role = "Member",
                            WeeklyCapacityHours = 40
                        });
                });

            modelBuilder.Entity("Weekwise.Core.Entities.WeeklyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("RndPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TechDebtPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<double>("TotalHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("WeekStartDate");

                    b.ToTable("WeeklyPlans");
                });

            modelBuilder.Entity("Weekwise.Core.Entities.WorkCommitment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BacklogItemId")
                        .HasColumnType("TEXT");

                    b.Property<double>("CommittedHours")
                        .HasColumnType("REAL");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WeeklyPlanId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacklogItemId");

                    b.HasIndex("MemberId");

                    b.HasIndex("WeeklyPlanId", "MemberId", "BacklogItemId")
                        .IsUnique();

                    b.ToTable("WorkCommitments");
                });

            modelBuilder.Entity("Weekwise.Core.Entities.PlanMember", b =>
                {
                    b.HasOne("Weekwise.Core.Entities.TeamMember", "Member")
                        .WithMany("PlanMemberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weekwise.Core.Entities.WeeklyPlan", "WeeklyPlan")
                        .WithMany("PlanMembers")
                        .HasForeignKey("WeeklyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("WeeklyPlan");
                });

            modelBuilder.Entity("Weekwise.Core.Entities.ProgressUpdate", b =>
                {
                    b.HasOne("Weekwise.Core.Entities.WorkCommitment", "WorkCommitment")
                        .WithMany("ProgressUpdates")
                        .HasForeignKey("WorkCommitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkCommitment");
                });

            modelBuilder.Entity("Weekwise.Core.Entities.WorkCommitment", b =>
                {
                    b.HasOne("Weekwise.Core.Entities.BacklogItem", "BacklogItem")
                        .WithMany("WorkCommitments")
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weekwise.Core.Entities.TeamMember", "Member")
                        .WithMany("WorkCommitments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weekwise.Core.Entities.WeeklyPlan", "WeeklyPlan")
                        .WithMany("WorkCommitments")
                        .HasForeignKey("WeeklyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacklogItem");

                    b.Navigation("Member");

                    b.Navigation("WeeklyPlan");
                });

            modelBuilder.Entity("Weekwise.Core.Entities.BacklogItem", b =>
                {
                    b.Navigation("WorkCommitments");
                });

            modelBuilder.Entity("Weekwise.Core.Entities.TeamMember", b =>
                {
                    b.Navigation("PlanMemberships");

                    b.Navigation("WorkCommitments");
                });

            modelBuilder.Entity("Weekwise.Core.Entities.WeeklyPlan", b =>
                {
                    b.Navigation("PlanMembers");

                    b.Navigation("WorkCommitments");
                });

            modelBuilder.Entity("Weekwise.Core.Entities.WorkCommitment", b =>
                {
                    b.Navigation("ProgressUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
